### PR TITLE
Added POM for Maven; however, there are intrinsic difficulties getting M...

### PR DESCRIPTION
**Pull request by zendawg**
...aven to work with sources and test classes in the same tree. Force installation by skipping tests.

### CODE REVIEW

**Comment by zendawg** [comment]
I'll take a further look into getting the tests to work inside of Maven another time; one option (not keen on this) is to split the src and test trees - but this would require modifying the ant build scripts. More than happy to do that, however, as a piece of work.

**Comment by dhowe** [comment]
actually a question, does maven have the concept of dev and/or optional dependencies?
there are no actual required dependencies for rita (snakeyaml is optional, junit is for testing only, etc)
how is this usually handled?

**Comment by zendawg** [comment]
Hi,

actually I didn't take an in-depth look at that - I'll change the scope of the Snake YAML dependency to 'test'. Also, I've made some more changes yesterday that have made a big improvement - I'll check them in and do a pull request sometime over the next few days. I'll also check the other dependencies and tidy them up too.

**Comment by dhowe** [comment]
Check out the changes I've made (removing a few dependencies and making sure things still compile correctly with -DskipTests)

Both SnakeYAML and Processing are runtime optional, but compile-time required, so perhaps they need to stay listed as dependencies...

**Comment by zendawg** [comment]
OK, thanks for that - I'll patch my changes in. TBH I needed it just to produce a library to start with for another project - but by the end of the week had to start digging into RiTa which is when I (finally!) had the chance to start getting in to the nitty gritty of it. There are a number of scopes I can apply to make these new changes work and to make the whole lib generation process more tidy now I have more knowledge of RiTa under-the-hood. Thanks!

**Pull request merged**
