### PR TITLE
Fix RiTaTwitterBot archive in Gallery

### PR DESCRIPTION
**Pull request by CyrusSUEN**

### CODE REVIEW

**Comment by dhowe** [comment]
all the links on gallery.php should be relative:
  href="./gallery/MemoireInvolontaireNo1"
  href="./gallery/RiTaTwitterbots/"
etc.

**Comment by CyrusSUEN** [comment]
The links are now in the format of "/rita/web/gallery/MemoireInvolontaireNo1".
It works on my local server as relative links. Does it work for you? 

If not, please merge with this PR: https://github.com/dhowe/RiTa/pull/269

**Comment by dhowe** [comment]
It did not work before. With #269, pages load correctly, but CSS is still broken for  "RiTaTwitterbots":

screen shot 2016-01-03 at 6 45 26 pm

**Comment by dhowe** [comment]
Further, their should be no external links for resources (this is the entire point of this task). Please remove all such links (to css, images, etc.)

**Comment by CyrusSUEN** [comment]
> should be no external links for resources
Tested with no Internet Connect, only TheWholeBrilliantEnterprise needs to be updated: https://github.com/dhowe/RiTa/pull/270

**Comment by CyrusSUEN** [comment]
> With #269, pages load correctly, but CSS is still broken for "RiTaTwitterbots":

So this is the technical difficulty I had (and still has), I thought it was brower's issue that sometimes by renaming the RiTaTwitterbots folder I can get it working correctly.

**Comment by dhowe** [comment]
check telegram

**Comment by CyrusSUEN** [comment]
Should be good now: https://github.com/dhowe/RiTa/pull/272

**Pull request merged**
