### PR TITLE
added instruction for using WordNet

### PR DESCRIPTION
**Pull request by CyrusSUEN**

### CODE REVIEW

**Comment by dhowe** [comment]
@cyrus,  did you actually test the code in these instructions? It doesn't work for me

Why are you specifying an absolute path (in the first example), but instructing users to put WordNet in their 'data' folder?

**Comment by CyrusSUEN** [comment]
I did test the code before writing the instruction.
It runs correctly on my Windows desktop.

But yes. I cannot get the example code for Processing to work on Mac.

**Comment by CyrusSUEN** [comment]
I'm downloading these to give it a try.
3.0a7 (26 April 2015) Mac OS X
3.0a5 (16 November 2014) Mac OS X

**Comment by dhowe** [comment]
As far as I can tell, you need to specify an absolute path to the directory, e.g., "/usr/lib/WordNet-3.1"

**Comment by dhowe** [comment]
Good ides -- please test all the installation instructions (rita, wordnet, rita-js) with Processing 3.0

**Comment by CyrusSUEN** [comment]
Still needs an absolute path on the 3.0a7.
Tested the following code and it still runs on Processing 3.0a7
```
import rita.*;

println(RiTa.tokenize("The elephant took a bite!"));
```

I will just change the instruction for WordNet to include an absolute path.

**Comment by dhowe** [comment]
Please check that you switch to 'processingjs mode' in Processing 3.0, and that the sketch above still works

**Pull request closed without merging**
