### PR TITLE
Text Analysis Example

### PR DESCRIPTION
**Pull request by cqx931**

### CODE REVIEW

**Comment by dhowe** [comment]
this is great -- but I want it to be "beautiful" ...
can you take a crack at a design? (maybe just a photoshop mockup?)
I was thinking that maybe we have a small/colorful image for each phoneme, 
first they assemble, then the fall, eventually disappearing off the bottom of the screen?

**Comment by dhowe** [comment]
Also please port this to javascript with p5js...

**Comment by cqx931** [comment]
I see. I will give it a try.

**Comment by cqx931** [comment]
artboard 1
Something like this?
Each circle is a phoneme. Several circles sticking together is a syllable.
If a syllable is on stress, the size of the circles would be bigger.
The circles first appear in the middle and fall to the bottom of the screen. When they disappear, it changes to the next word.
The Tag on the left corner is for the pos tag.

**Comment by dhowe** [comment]
looks good!

**Pull request merged**
