### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by CyrusSUEN**

### CODE REVIEW

**Comment by dhowe** [comment]
In the future, no need to create Java + JS examples unless they are actually different calls... See my updates to the functions above and confirm that you read this...

**Comment by CyrusSUEN** [comment]
> no need to create Java + JS examples unless they are actually different calls

Understood. But I do not see any updates to the functions yet.

**Comment by dhowe** [comment]
http://rednoise.org/rita/reference/RiTa/RiTa.tokenize/index.php <http://rednoise.org/rita/reference/RiTa/RiTa.tokenize/index.php>

**Comment by CyrusSUEN** [comment]
You are right that the other 3 do not require a separate version, but for the RiTa.tokenize(), I think it needs separate Java and JS examples.

Java:
```java
wordArray = RiTa.tokenize(sentence, "\\s");
```
JS:
```js
wordArray = RiTa.tokenize(sentence, /\s/);
```

**Comment by dhowe** [comment]
ok

On October 17, 2015 3:58:53 PM GMT+08:00, Cyrus S <notifications@github.com> wrote:
>You are right that the other 3 do not require a separate version, but
>for the RiTa.tokenize(), I think it needs separate Java and JS
>examples.
>
>Java:
>```java
>wordArray = RiTa.tokenize(sentence, "\\s");
>```
>JS:
>```js
>wordArray = RiTa.tokenize(sentence, /\s/);
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dhowe/RiTa/pull/234#issuecomment-148893962


[mobile]

**Pull request merged**
